@startuml BILL_PAY_TO_NEW_ACCOUNT_SCENARIO
!pragma teoz true
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor JohnUser as user

participant "Read Login Data" as read_login_data #TECHNOLOGY
participant "Login" as login #APPLICATION
participant "Create Account Data Set" as create_account_dt #TECHNOLOGY
participant "Open New Account" as account #BUSINESS
participant "Update Account Data Set" as update_account_dt #TECHNOLOGY
participant "Create Bill Pay Data Set" as create_billpay_dt #TECHNOLOGY
participant "Update Bill Pay Data Set" as update_billpay_dt #TECHNOLOGY
participant "Bill Pay" as billpay #BUSINESS
participant "Merge DataTables" as merge_dts #TECHNOLOGY

user -> read_login_data: <<LOGIN_DATA_PATH>>
activate read_login_data
return <<login_data>>
deactivate read_login_data

user -> login: <<URL>> <<USERNAME>> <<PASSWORD>>
activate login
user <- login
deactivate login

user -> create_account_dt: <<ACCOUNT_DATA_PATH>> <<ACCOUNT_DATA_INDEX>>
activate create_account_dt
return <<account_dt>>
deactivate create_account_dt

user -> account: <<account_dt>>
activate account
account --> user: <<account_opened>>
deactivate account

user -> update_account_dt: <<account_dt>> <<ACCOUNT_OPENED=<<account_opened>>>>
activate update_account_dt
update_account_dt --> user: <<account_dt_updated>>
deactivate update_account_dt


user -> create_billpay_dt: <<BILL_PAY_DATA_PATH>> <<BILL_PAY_DATA_INDEX>>
activate create_billpay_dt
return <<billpay_dt>>
deactivate create_billpay_dt

user -> update_billpay_dt: <<billpay_dt>> <<PAYEE_ACCOUNT=<<account_opened>>>> <<PAYEE_VERIFIY_ACCOUNT=<<account_opened>>>>
activate update_billpay_dt
update_billpay_dt --> user: <<billpay_dt_updated>>
deactivate update_billpay_dt

user -> billpay: <<billpay_dt_updated>>
activate billpay
billpay --> user
deactivate billpay

user -> merge_dts: <<account_dt_updated>> <<billpay_dt_updated>>
activate merge_dts
merge_dts --> user: <<usecase_dt>>
deactivate merge_dts

@enduml