@startuml BILL_PAY_TO_NEW_ACCOUNT_USECASE
left to right direction
skinparam actorStyle awesome

actor JohnUser as user

package "Bill Pay To New Account From Existing Account" {
    usecase (Login)/ as login
    usecase (Open New Account)/ as account
    usecase (Bill Pay)/ as billpay
}

user --> account
user --> billpay
account --> login: <<include>>
billpay --> login: <<include>>
@enduml