@startuml REQUEST_LOAN_E2E
rectangle "Request Loan" {
    partition "Account Services Page" {
        :Add Info To Report;
        :Click On "Request Loan";
    }
    partition "Request Loan Page" {
        :Enter [Loan Amount]; <<input>>
        :Enter [Down Amount]; <<input>>
        :Select [From Account]; <<input>>
        :Add Info To Report;
        :Click On "APPLY NOW";
        if (Did The Loan Approved Message Appear?) then (YES)
            :Save [Account Number Loan] value; <<save>>
            :Add Pass To Report;
            #palegreen:Use Case Has Been Completed;
        else (NO)
            :Add Error To Report;
            #pink:Use Case Has Failed;
            stop
        endif
    }
}
@enduml