@startuml OVERVIEW_OF_A_BILL_PAY_TO_EXISTING_ACCOUNT_USECASE
left to right direction
skinparam actorStyle awesome

actor JohnUser as user

package "Account Overview Of A Bill Pay To Existing Account From New Account" {
    usecase (Login)/ as login
    usecase (Open New Account)/ as account
    usecase (Bill Pay)/ as billpay
    usecase (Accounts Overview)/ as overview
}

user --> account
user --> billpay
user --> overview

account --> login: <<include>>
billpay --> login: <<include>>
overview --> login: <<include>>
@enduml